# Allow requests from these domains
allow-origins: 
  - http://localhost
  - http://localhost:3000
  - http://localhost:57875
  - http://10.0.0.97
  
# Url to Auth Server
auth-url: http://localhost:8002

auth-access-token: kjhsdagfkjshhfksjhfdalkjd

mail-service-token: TestToken123

mail-service-url: http://localhost:8005